/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BettingPools } from "./BettingPools";
export * as factories from "./factories";
export { BettingPools__factory } from "./factories/BettingPools__factory";
